version: '3' 
services: 
  jira:
    container_name: jira 
    image: atlassian/jira-software:latest 
    volumes: 
     - jira_home:/var/atlassian/application-data/jira
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http 

  confluence: 
    container_name: confluence
    image: atlassian/confluence-server:latest
    volumes: 
      - confluence_home:/var/atlassian/application-data/confluence
    environment: 
     - ATL_PROXY_NAME=confluence.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http

#  bitbucket: 
#    container_name: bitbucket 
#    image: atlassian/bitbucket-server:latest 
#    environment: 
#     - SERVER_PROXY_NAME=bitbucket.internal
#     - SERVER_PROXY_PORT=80
#     - SERVER_SCHEME=http 

  nginx: 
    container_name: nginx 
#    image: nginx:latest 
#    volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf 
    build: nginx
    depends_on: 
     - jira 
     - confluence 
#     - bitbucket 
    ports: 
     - "80:80" 
    networks: 
      default: 
        aliases:
         - jira.internal
         - confluence.internal
#         - bitbucket.internal 
volumes:
  jira_home:
  confluence_home:
